# Generated by Django 5.1.4 on 2026-04-19 10:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0014_user_last_activity_at_user_last_activity_ip'),
        ('payments', '0006_add_swap_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='referral_code', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('code', models.CharField(db_index=True, max_length=8, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Admin kill switch — disables sharing + attribution for abusers.')),
                ('total_invites_sent', models.PositiveIntegerField(default=0, help_text='Client-reported share events. Informational only.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Referral Code',
                'verbose_name_plural': 'Referral Codes',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_used', models.CharField(help_text='Denormalised — survives ReferralCode.code changes/revokes.', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('signed_up', 'Signed up'), ('qualified', 'Qualified'), ('rewarded', 'Rewarded'), ('clawed_back', 'Clawed back'), ('rejected_fraud', 'Rejected (fraud)')], db_index=True, default='signed_up', max_length=20)),
                ('signup_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('signup_device_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('signup_country', models.CharField(blank=True, max_length=2)),
                ('signup_user_agent', models.TextField(blank=True)),
                ('attributed_at', models.DateTimeField(auto_now_add=True)),
                ('qualified_at', models.DateTimeField(blank=True, null=True)),
                ('rewarded_at', models.DateTimeField(blank=True, null=True)),
                ('attribution_window_ends_at', models.DateTimeField(help_text='Hard deadline: referee must qualify before this or the referral dies.')),
                ('fraud_reason', models.TextField(blank=True)),
                ('qualifying_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payments.transaction')),
                ('referee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='was_referred_by', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
            },
        ),
        migrations.CreateModel(
            name='ReferralEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('code_viewed', 'Code Viewed'), ('code_shared', 'Code Shared'), ('link_clicked', 'Link Clicked'), ('signup_attributed', 'Signup Attributed'), ('qualified', 'Qualified'), ('rewarded', 'Rewarded'), ('clawed_back', 'Clawed Back'), ('fraud_flagged', 'Fraud Flagged'), ('credit_consumed', 'Credit Consumed'), ('credit_expired', 'Credit Expired')], db_index=True, max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=128)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='referrals.referral')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Event',
                'verbose_name_plural': 'Referral Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_kes', models.DecimalField(decimal_places=2, help_text='Positive for credits, negative for clawbacks/consumption.', max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('kind', models.CharField(choices=[('referrer_bonus', 'Referrer bonus'), ('referee_bonus', 'Referee bonus'), ('admin_grant', 'Admin grant'), ('clawback', 'Clawback (negative adj)'), ('consumed', 'Consumed (negative)')], max_length=24)),
                ('status', models.CharField(choices=[('held', 'Held'), ('available', 'Available'), ('consumed', 'Consumed'), ('clawed_back', 'Clawed back'), ('expired', 'Expired')], db_index=True, max_length=16)),
                ('held_until', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('idempotency_key', models.CharField(help_text="e.g. 'ref:{referral_id}:referrer'. Blocks double-grants.", max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('consumed_by_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payments.transaction')),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='referrals.referral')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_ledger', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reward Ledger Entry',
                'verbose_name_plural': 'Reward Ledger',
            },
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referrer', 'status'], name='referrals_r_referre_ebbb80_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['status', 'attributed_at'], name='referrals_r_status_199253_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardledger',
            index=models.Index(fields=['user', 'status'], name='referrals_r_user_id_3e3688_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardledger',
            index=models.Index(fields=['status', 'held_until'], name='referrals_r_status_1cecb4_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardledger',
            index=models.Index(fields=['status', 'expires_at'], name='referrals_r_status_9528bf_idx'),
        ),
    ]
