# Generated by Django 5.1.4 on 2026-03-08 08:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wallet_type', models.CharField(choices=[('hot', 'Hot'), ('fee', 'Fee'), ('float', 'Float')], max_length=10)),
                ('currency', models.CharField(choices=[('USDT', 'Usdt'), ('USDC', 'Usdc'), ('BTC', 'Btc'), ('ETH', 'Eth'), ('SOL', 'Sol'), ('KES', 'Kes')], max_length=10)),
                ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=28)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_wallets',
                'unique_together': {('wallet_type', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(choices=[('USDT', 'Usdt'), ('USDC', 'Usdc'), ('BTC', 'Btc'), ('ETH', 'Eth'), ('SOL', 'Sol'), ('KES', 'Kes')], max_length=10)),
                ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=28)),
                ('locked_balance', models.DecimalField(decimal_places=8, default=0, max_digits=28)),
                ('deposit_address', models.CharField(blank=True, max_length=255)),
                ('address_index', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.UUIDField(db_index=True)),
                ('entry_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=28)),
                ('balance_after', models.DecimalField(decimal_places=8, max_digits=28)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='wallets.wallet')),
            ],
            options={
                'db_table': 'ledger_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='wallet_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('locked_balance__gte', 0)), name='wallet_locked_balance_non_negative'),
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('user', 'currency')},
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ledger_amount_positive'),
        ),
    ]
