# Generated by Django 5.1.4 on 2026-03-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_rebalance_order'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rebalanceorder',
            new_name='rebalance_o_status_ffdce7_idx',
            old_name='rebalance_o_status_idx',
        ),
        migrations.RenameIndex(
            model_name='rebalanceorder',
            new_name='rebalance_o_created_f4e79d_idx',
            old_name='rebalance_o_created_idx',
        ),
        migrations.AddConstraint(
            model_name='systemwallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='system_wallet_balance_non_negative'),
        ),
    ]
