# Generated by Django 5.1.4 on 2026-03-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_custody_tiers'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='custodytransfer',
            new_name='custody_tra_status_2cf3a5_idx',
            old_name='custody_tra_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='custodytransfer',
            new_name='custody_tra_from_ti_2bd70f_idx',
            old_name='custody_tra_tiers_idx',
        ),
        migrations.RenameIndex(
            model_name='custodytransfer',
            new_name='custody_tra_created_ff2a79_idx',
            old_name='custody_tra_created_idx',
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(fields=('transaction_id', 'wallet_id', 'entry_type'), name='ledger_idempotent_entry'),
        ),
    ]
