# Generated by Django 5.1.4 on 2026-05-16 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0007_remove_deposit_address_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemwallet',
            name='wallet_type',
            field=models.CharField(choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold'), ('fee', 'Fee'), ('float', 'Float'), ('provider_cost', 'Provider Cost'), ('excise', 'Excise'), ('gas_reserve', 'Gas Reserve')], max_length=20),
        ),
        migrations.CreateModel(
            name='FeeLedgerEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.UUIDField(db_index=True, help_text='Source Transaction.id whose completion booked this entry. Used for idempotency (same tx_id + same system_wallet + same entry_type cannot create two entries).')),
                ('entry_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=28)),
                ('balance_after', models.DecimalField(decimal_places=8, max_digits=28)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('system_wallet', models.ForeignKey(help_text='Which SystemWallet (fee / provider_cost / excise / gas_reserve) this movement targets.', on_delete=django.db.models.deletion.PROTECT, related_name='fee_ledger_entries', to='wallets.systemwallet')),
            ],
            options={
                'db_table': 'fee_ledger_entries',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='fee_ledger_amount_positive'), models.UniqueConstraint(fields=('transaction_id', 'system_wallet', 'entry_type'), name='fee_ledger_idempotent_entry')],
            },
        ),
    ]
