# Generated by Django 5.1.4 on 2026-03-08 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaCallback',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('merchant_request_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('result_code', models.IntegerField(null=True)),
                ('result_desc', models.TextField(blank=True)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_callbacks', to='payments.transaction')),
            ],
            options={
                'db_table': 'mpesa_callbacks',
            },
        ),
    ]
