# Generated by Django 5.1.4 on 2026-04-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0001_initial'),
        ('payments', '0006_add_swap_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesacallback',
            name='mpesa_receipt',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddConstraint(
            model_name='mpesacallback',
            constraint=models.UniqueConstraint(condition=models.Q(('mpesa_receipt', ''), _negated=True), fields=('mpesa_receipt',), name='mpesa_callback_unique_nonempty_receipt'),
        ),
    ]
