# Generated by Django 5.1.4 on 2026-03-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(db_index=True, max_length=20)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('source', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'exchange_rates',
                'ordering': ['-created_at'],
            },
        ),
    ]
