# Generated by Django 5.1.4

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rates", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RateAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USDT", "USDT"),
                            ("BTC", "BTC"),
                            ("ETH", "ETH"),
                            ("SOL", "SOL"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "target_rate",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Target KES rate",
                        max_digits=18,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("above", "Above"), ("below", "Below")],
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("triggered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "rate_alerts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "currency"],
                        name="ratealert_active_currency",
                    ),
                ],
            },
        ),
    ]
