# Generated by Django 5.1.4 on 2026-04-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0004_ratealert_schedule_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratealert',
            name='currency',
            field=models.CharField(choices=[('USDT', 'USDT'), ('USDC', 'USDC'), ('BTC', 'BTC'), ('ETH', 'ETH'), ('SOL', 'SOL')], max_length=10),
        ),
    ]
