# Generated by Django 5.1.4 on 2026-03-12 20:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_device_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='PINResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pin_reset_tokens',
            },
        ),
    ]
