# Generated by Django 5.1.4 on 2026-03-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_suspension_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='otp_code',
            field=models.CharField(db_index=True, default='', max_length=6),
        ),
    ]
