# Generated by Django 5.1.4 on 2026-03-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_reduce_fullname_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
