# Generated by Django 5.1.4 on 2026-04-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_activity_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
