# Generated by Django 5.1.4 on 2026-04-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_language_notify_prefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_platform',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16),
        ),
    ]
