# Generated by Django 5.1.4 on 2026-03-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainDeposit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chain', models.CharField(db_index=True, max_length=20)),
                ('tx_hash', models.CharField(max_length=100)),
                ('from_address', models.CharField(blank=True, max_length=100)),
                ('to_address', models.CharField(db_index=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=28)),
                ('currency', models.CharField(max_length=10)),
                ('confirmations', models.IntegerField(default=0)),
                ('required_confirmations', models.IntegerField()),
                ('status', models.CharField(choices=[('detecting', 'Detecting'), ('confirming', 'Confirming'), ('confirmed', 'Confirmed'), ('credited', 'Credited')], default='detecting', max_length=20)),
                ('credited_at', models.DateTimeField(blank=True, null=True)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('block_hash', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blockchain_deposits',
                'unique_together': {('chain', 'tx_hash')},
            },
        ),
    ]
