# Generated by Django 5.1.4 on 2026-03-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_sweeporder'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sweeporder',
            name='unique_active_sweep_per_address',
        ),
        migrations.AddConstraint(
            model_name='sweeporder',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'submitted', 'confirming'])), fields=('chain', 'from_address'), name='unique_active_sweep_per_address'),
        ),
    ]
