# Generated by Django 5.1.4 on 2026-03-08 08:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('BUY', 'Buy'), ('SELL', 'Sell'), ('PAYBILL_PAYMENT', 'Paybill Payment'), ('TILL_PAYMENT', 'Till Payment'), ('SEND_MPESA', 'Send Mpesa'), ('INTERNAL_TRANSFER', 'Internal Transfer'), ('FEE', 'Fee')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('confirming', 'Confirming'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=20)),
                ('source_currency', models.CharField(blank=True, max_length=10)),
                ('source_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=28, null=True)),
                ('dest_currency', models.CharField(blank=True, max_length=10)),
                ('dest_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=28, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('fee_amount', models.DecimalField(decimal_places=8, default=0, max_digits=28)),
                ('fee_currency', models.CharField(blank=True, max_length=10)),
                ('mpesa_paybill', models.CharField(blank=True, max_length=20)),
                ('mpesa_till', models.CharField(blank=True, max_length=20)),
                ('mpesa_account', models.CharField(blank=True, max_length=50)),
                ('mpesa_phone', models.CharField(blank=True, max_length=15)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=30)),
                ('chain', models.CharField(blank=True, max_length=20)),
                ('tx_hash', models.CharField(blank=True, max_length=100)),
                ('confirmations', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('saga_step', models.SmallIntegerField(default=0)),
                ('saga_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
