# Generated by Django 5.1.4 on 2026-03-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='excise_duty_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=28),
        ),
    ]
