# Generated by Django 5.1.4

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_add_composite_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedPaybill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("paybill_number", models.CharField(max_length=20)),
                ("account_number", models.CharField(max_length=50)),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="e.g. KPLC Home, DSTV",
                        max_length=100,
                    ),
                ),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_paybills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "saved_paybills",
                "ordering": ["-last_used_at", "-created_at"],
                "unique_together": {("user", "paybill_number", "account_number")},
            },
        ),
    ]
