# Generated by Django 5.1.4 on 2026-04-26 16:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_add_swap_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='has_open_reconciliation',
            field=models.BooleanField(db_index=True, default=False, help_text='True while at least one ReconciliationCase row is OPEN/ESCALATED for this tx.'),
        ),
        migrations.CreateModel(
            name='ReconciliationCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_type', models.CharField(choices=[('double_settlement', 'Double settlement'), ('late_callback', 'Late callback'), ('orphan_b2b', 'Orphan B2B'), ('compensate_failed', 'Compensation failed'), ('reversal_not_supported', 'Reversal not supported')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('auto_resolved', 'Auto-resolved'), ('human_resolved', 'Human-resolved'), ('escalated', 'Escalated')], db_index=True, default='open', max_length=16)),
                ('severity', models.IntegerField(choices=[(1, 'Info'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Critical · page on-call')], default=4)),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sla_breach_at', models.DateTimeField(blank=True, help_text='When this case crosses its SLO · auto-escalation trigger.', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_action', models.CharField(blank=True, default='', help_text='reverse_refund / b2c_clawback / write_off / human_review / not_applicable', max_length=32)),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', help_text='Saga correlation ID · ties together every log line, retry, and alert for this case.', max_length=64)),
                ('evidence', models.JSONField(blank=True, default=dict, help_text='Both callback payloads, timestamps, amounts, ABI codes, etc.')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_recon_cases', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recon_cases', to='payments.transaction')),
            ],
            options={
                'db_table': 'reconciliation_cases',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['status', '-severity', 'detected_at'], name='recon_open_sev'), models.Index(fields=['status', 'sla_breach_at'], name='recon_sla_sweep')],
            },
        ),
    ]
